#!/bin/sh
export LANG=en.US.UTF-8

#for choosing Begali Language (Language of Bangladesh)
export LANG=bn_BD.UTF-8

LANG=en_US

language=$(zenity --entry --entry-text="Type" --text="Please Choose language: Type B for Bengali ; Type E for English")

if [ "$language" == "B" ]
then

{
LANG=bn_BD

continent=$(zenity --list \
 --title="মহাদেশের নাম" \
 --column="মহদেশ" \
Africa \
Americas \
Antarctica \
Asia \
Australia \
Europe)
city=$(zenity --list \
 --title="শহরের নাম" \
 --column="শহর" \
Abuja \
Accra \
Adamstown \
Addis_Ababa \
Algiers \
Amsterdam \
Ankara \
Apia \
Athens \
Baghdad \
Bangkok \
Beirut \
Belgrade \
Berlin \
Bissau \
Brasília \
Brussels \
Bucharest \
Budapest \
Cairo \
Canberra \
Caracas \
Copenhagen \
Dakar \
Dhaka \
Djibouti \
Doha \
Dublin \
Helsinki \
Islamabad \
Jakarta \
Kampala \
Kiev \
Lima \
Lisbon \
Luxembourg \
Madrid \
Moscow \
Nairobi \
Prague \
Riga \
Riyadh \
Rome \
Seoul \
Singapore \
Sofia \
Stockholm \
Taipei \
Tallinn \
Tehran \
Tokyo \
Vatican \
Vienna)
export TZ="$continent"/"$city"
date=$(date)
zenity --info --title="Clock" --text="Date and Time: $date"

}

elif [ "$language" == "E" ]
then
{
export LANG=en_US.UTF-8
LANG=en_US

continent=$(zenity --list \
 --title="Choose your Continent" \
 --column="Continent Name" \
Africa \
Americas \
Antarctica \
Asia \
Australia \
Europe)
city=$(zenity --list \
 --title="Choose your City" \
 --column="City Name" \
Abuja \
Accra \
Adamstown \
Addis_Ababa \
Algiers \
Amsterdam \
Ankara \
Apia \
Athens \
Baghdad \
Bangkok \
Beirut \
Belgrade \
Berlin \
Bissau \
Brasília \
Brussels \
Bucharest \
Budapest \
Cairo \
Canberra \
Caracas \
Copenhagen \
Dakar \
Dhaka \
Djibouti \
Doha \
Dublin \
Helsinki \
Islamabad \
Jakarta \
Kampala \
Kiev \
Lima \
Lisbon \
Luxembourg \
Madrid \
Moscow \
Nairobi \
Prague \
Riga \
Riyadh \
Rome \
Seoul \
Singapore \
Sofia \
Stockholm \
Taipei \
Tallinn \
Tehran \
Tokyo \
Vatican \
Vienna)
export TZ="$continent"/"$city"
date=$(date)
zenity --info --title="Clock" --text="Date and Time: $date"

}
fi
